spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/virus?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Admin123@zh
    driver-class-name: com.mysql.cj.jdbc.Driver
    #初始化连接
    initial-size: 10
    #最大空闲连接
    max-idle: 20
    #最小空闲连接
    min-idle: 5
    #最大连接数量
    max-active: 100
    #配置获取连接等待超时的时间以毫秒为单位
    max-wait: 300000
    test-while-idle: true
    #检测数据库的查询语句
    validation-query: select 1 from dual
    test-on-borrow: true
    #配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 600000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 300000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
system:
  file-path: D:\kemyond\kysoc\virus